// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXT17HBIG7JM9R_PP6bfifSR-utBFtaSE',
    appId: '1:245986508663:web:e88d16407497533ea4ab72',
    messagingSenderId: '245986508663',
    projectId: 'beawake-a1aa6',
    authDomain: 'beawake-a1aa6.firebaseapp.com',
    storageBucket: 'beawake-a1aa6.appspot.com',
    measurementId: 'G-7FFH3EKQWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6OyTykC28lRr9f6XBafEdM9NuP_OjsBo',
    appId: '1:245986508663:android:055efa1bd1572078a4ab72',
    messagingSenderId: '245986508663',
    projectId: 'beawake-a1aa6',
    storageBucket: 'beawake-a1aa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmD2HNTSED3u69l5fxiYxi8XghJVRD8LI',
    appId: '1:245986508663:ios:e6d0ee965376fe0aa4ab72',
    messagingSenderId: '245986508663',
    projectId: 'beawake-a1aa6',
    storageBucket: 'beawake-a1aa6.appspot.com',
    iosBundleId: 'com.example.beawake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmD2HNTSED3u69l5fxiYxi8XghJVRD8LI',
    appId: '1:245986508663:ios:e6d0ee965376fe0aa4ab72',
    messagingSenderId: '245986508663',
    projectId: 'beawake-a1aa6',
    storageBucket: 'beawake-a1aa6.appspot.com',
    iosBundleId: 'com.example.beawake',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXT17HBIG7JM9R_PP6bfifSR-utBFtaSE',
    appId: '1:245986508663:web:b57c46390369a872a4ab72',
    messagingSenderId: '245986508663',
    projectId: 'beawake-a1aa6',
    authDomain: 'beawake-a1aa6.firebaseapp.com',
    storageBucket: 'beawake-a1aa6.appspot.com',
    measurementId: 'G-2XSCW7T5DR',
  );
}
